part of '../currency.dart';

final Map<String, Currency> _currencyMap = {
  'AED': const Currency(
    code: 'AED',
    englishName: 'United Arab Emirates Dirham',
    precision: 2,
    emoji: '🇦🇪',
    symbol: 'Dh',
  ),
  'AFN': const Currency(
    code: 'AFN',
    englishName: 'Afghan Afghani',
    precision: 2,
    emoji: '🇦🇫',
  ),
  'ALL': const Currency(
    code: 'ALL',
    englishName: 'Albanian Lek',
    precision: 2,
    emoji: '🇦🇱',
  ),

  'AMD': const Currency(
    code: 'AMD',
    englishName: 'Armenian Dram',
    precision: 2,
    emoji: '🇦🇲',
  ),
  'ANG': const Currency(
    code: 'ANG',
    englishName: 'Netherlands Antillean Guilder',
    precision: 2,
    emoji: '🇳🇱',
  ),
  'AOA': const Currency(
    code: 'AOA',
    englishName: 'Angolan Kwanza',
    precision: 2,
    emoji: '🇦🇴',
  ),
  'ARS': const Currency(
    code: 'ARS',
    englishName: 'Argentine Peso',
    precision: 2,
    emoji: '🇦🇷',
  ),
  'AUD': const Currency(
    code: 'AUD',
    englishName: 'Australian Dollar',
    precision: 2,
    emoji: '🇦🇺',
  ),
  'AWG': const Currency(
    code: 'AWG',
    englishName: 'Aruban Florin',
    precision: 2,
    emoji: '🇦🇼',
  ),
  'AZN': const Currency(
    code: 'AZN',
    englishName: 'Azerbaijani Manat',
    precision: 2,
    emoji: '🇦🇿',
  ),
  'BAM': const Currency(
    code: 'BAM',
    englishName: 'Bosnia and Herzegovina Convertible Mark',
    precision: 2,
    emoji: '🇧🇦',
  ),
  'BBD': const Currency(
    code: 'BBD',
    englishName: 'Barbadian Dollar',
    precision: 2,
    emoji: '🇧🇧',
  ),
  'BDT': const Currency(
    code: 'BDT',
    englishName: 'Bangladeshi Taka',
    precision: 2,
    emoji: '🇧🇩',
  ),
  'BGN': const Currency(
    code: 'BGN',
    englishName: 'Bulgarian Lev',
    precision: 2,
    emoji: '🇧🇬',
  ),
  'BHD': const Currency(
    code: 'BHD',
    englishName: 'Bahraini Dinar',
    precision: 3,
    emoji: '🇧🇭',
  ),
  'BIF': const Currency(
    code: 'BIF',
    englishName: 'Burundian Franc',
    precision: 2,
    emoji: '🇧🇮',
  ),
  'BMD': const Currency(
    code: 'BMD',
    englishName: 'Bermudian Dollar',
    precision: 2,
    emoji: '🇧🇲',
  ),
  'BND': const Currency(
    code: 'BND',
    englishName: 'Brunei Dollar',
    precision: 1,
    emoji: '🇧🇳',
  ),
  'BOB': const Currency(
    code: 'BOB',
    englishName: 'Bolivian Boliviano',
    precision: 2,
    emoji: '🇧🇴',
  ),
  'BRL': const Currency(
    code: 'BRL',
    englishName: 'Brazilian Real',
    precision: 2,
    emoji: '🇧🇷',
  ),
  'BSD': const Currency(
    code: 'BSD',
    englishName: 'Bahamian Dollar',
    precision: 2,
    emoji: '🇧🇸',
  ),
  'BTN': const Currency(
    code: 'BTN',
    englishName: 'Bhutanese Ngultrum',
    precision: 2,
    emoji: '🇧🇹',
  ),
  'BWP': const Currency(
    code: 'BWP',
    englishName: 'Botswana Pula',
    precision: 2,
    emoji: '🇧🇼',
  ),
  'BYN': const Currency(
    code: 'BYN',
    englishName: 'Belarusian Ruble',
    precision: 2,
    emoji: '🇧🇾',
  ),
  'BZD': const Currency(
    code: 'BZD',
    englishName: 'Belize Dollar',
    precision: 2,
    emoji: '🇧🇿',
  ),
  'CAD': const Currency(
    code: CurrencyCodes.cad,
    englishName: 'Canadian Dollar',
    precision: 2,
    emoji: '🇨🇦',
  ),
  'CDF': const Currency(
    code: 'CDF',
    englishName: 'Congolese Franc',
    precision: 2,
    emoji: '🇨🇩',
  ),
  'CHF': const Currency(
    code: CurrencyCodes.chf,
    englishName: 'Swiss Franc',
    precision: 2,
    emoji: '🇨🇭',
    symbol: 'Fr',
  ),
  'CLP': const Currency(
    code: 'CLP',
    englishName: 'Chilean Peso',
    precision: 2,
    emoji: '🇨🇱',
  ),
  'CNY': const Currency(
    code: CurrencyCodes.cny,
    englishName: 'Chinese Yuan',
    precision: 1,
    emoji: '🇨🇳',
  ),
  'COP': const Currency(
    code: 'COP',
    englishName: 'Colombian Peso',
    precision: 2,
    emoji: '🇨🇴',
  ),
  'CRC': const Currency(
    code: 'CRC',
    englishName: 'Costa Rican Colón',
    precision: 2,
    emoji: '🇨🇷',
  ),
  'CUP': const Currency(
    code: 'CUP',
    englishName: 'Cuban Peso',
    precision: 2,
    emoji: '🇨🇺',
  ),
  'CVE': const Currency(
    code: 'CVE',
    englishName: 'Cape Verdean Escudo',
    precision: 2,
    emoji: '🇨🇻',
  ),
  'CZK': const Currency(
    code: 'CZK',
    englishName: 'Czech Koruna',
    precision: 2,
    emoji: '🇨🇿',
  ),
  'DJF': const Currency(
    code: 'DJF',
    englishName: 'Djiboutian Franc',
    precision: 2,
    emoji: '🇩🇯',
  ),
  'DKK': const Currency(
    code: 'DKK',
    englishName: 'Danish Krone',
    precision: 2,
    emoji: '🇩🇰',
  ),
  'DOP': const Currency(
    code: 'DOP',
    englishName: 'Dominican Peso',
    precision: 2,
    emoji: '🇩🇴',
  ),
  'DZD': const Currency(
    code: 'DZD',
    englishName: 'Algerian Dinar',
    precision: 2,
    emoji: '🇩🇿',
  ),
  'EGP': const Currency(
    code: 'EGP',
    englishName: 'Egyptian Pound',
    precision: 2,
    emoji: '🇪🇬',
  ),
  'ERN': const Currency(
    code: 'ERN',
    englishName: 'Eritrean Nakfa',
    precision: 2,
    emoji: '🇪🇷',
  ),
  'ETB': const Currency(
    code: 'ETB',
    englishName: 'Ethiopian Birr',
    precision: 2,
    emoji: '🇪🇹',
  ),
  'EUR': const Currency(
    code: CurrencyCodes.eur,
    englishName: 'Euro',
    precision: 2,
    emoji: '🇪🇺',
    symbol: '€',
  ),
  'FJD': const Currency(
    code: 'FJD',
    englishName: 'Fijian Dollar',
    precision: 2,
    emoji: '🇫🇯',
  ),
  'FKP': const Currency(
    code: 'FKP',
    englishName: 'Falkland Islands Pound',
    precision: 2,
    emoji: '🇫🇰',
  ),
  'GBP': const Currency(
    code: CurrencyCodes.gbp,
    englishName: 'British Pound Sterling',
    precision: 2,
    emoji: '🇬🇧',
    symbol: '£',
  ),
  'GEL': const Currency(
    code: 'GEL',
    englishName: 'Georgian Lari',
    precision: 2,
    emoji: '🇬🇪',
  ),
  'GHS': const Currency(
    code: 'GHS',
    englishName: 'Ghanaian Cedi',
    precision: 2,
    emoji: '🇬🇭',
  ),
  'GIP': const Currency(
    code: 'GIP',
    englishName: 'Gibraltar Pound',
    precision: 2,
    emoji: '🇬🇮',
  ),
  'GMD': const Currency(
    code: 'GMD',
    englishName: 'Gambian Dalasi',
    precision: 2,
    emoji: '🇬🇲',
  ),
  'GNF': const Currency(
    code: 'GNF',
    englishName: 'Guinean Franc',
    precision: 2,
    emoji: '🇬🇳',
  ),
  'GTQ': const Currency(
    code: 'GTQ',
    englishName: 'Guatemalan Quetzal',
    precision: 2,
    emoji: '🇬🇹',
  ),
  'GYD': const Currency(
    code: 'GYD',
    englishName: 'Guyanese Dollar',
    precision: 2,
    emoji: '🇬🇾',
  ),
  'HKD': const Currency(
    code: CurrencyCodes.hkd,
    englishName: 'Hong Kong Dollar',
    precision: 2,
    emoji: '🇭🇰',
  ),
  'HNL': const Currency(
    code: 'HNL',
    englishName: 'Honduran Lempira',
    precision: 2,
    emoji: '🇭🇳',
  ),
  'HRK': const Currency(
    code: 'HRK',
    englishName: 'Croatian Kuna',
    precision: 2,
    emoji: '🇭🇷',
  ),
  'HTG': const Currency(
    code: 'HTG',
    englishName: 'Haitian Gourde',
    precision: 2,
    emoji: '🇭🇹',
  ),
  'HUF': const Currency(
    code: 'HUF',
    englishName: 'Hungarian Forint',
    precision: 2,
    emoji: '🇭🇺',
  ),
  'IDR': const Currency(
    code: 'IDR',
    englishName: 'Indonesian Rupiah',
    precision: 2,
    emoji: '🇮🇩',
  ),
  'ILS': const Currency(
    code: 'ILS',
    englishName: 'Israeli New Shekel',
    precision: 2,
    emoji: '🇮🇱',
    symbol: '₪',
  ),
  'INR': const Currency(
    code: CurrencyCodes.inr,
    englishName: 'Indian Rupee',
    precision: 2,
    emoji: '🇮🇳',
    symbol: '₹',
  ),
  'IQD': const Currency(
    code: 'IQD',
    englishName: 'Iraqi Dinar',
    precision: 3,
    emoji: '🇮🇶',
  ),
  'IRR': const Currency(
    code: 'IRR',
    englishName: 'Iranian Rial',
    precision: 0,
    emoji: '🇮🇷',
  ),
  'ISK': const Currency(
    code: 'ISK',
    englishName: 'Icelandic Króna',
    precision: 2,
    emoji: '🇮🇸',
  ),
  'JMD': const Currency(
    code: 'JMD',
    englishName: 'Jamaican Dollar',
    precision: 2,
    emoji: '🇯🇲',
  ),
  'JOD': const Currency(
    code: 'JOD',
    englishName: 'Jordanian Dinar',
    precision: 2,
    emoji: '🇯🇴',
  ),
  'JPY': const Currency(
    code: CurrencyCodes.jpy,
    englishName: 'Japanese Yen',
    precision: 2,
    emoji: '🇯🇵',
  ),
  'KES': const Currency(
    code: 'KES',
    englishName: 'Kenyan Shilling',
    precision: 2,
    emoji: '🇰🇪',
  ),
  'KGS': const Currency(
    code: 'KGS',
    englishName: 'Kyrgyzstani Som',
    precision: 2,
    emoji: '🇰🇬',
  ),
  'KHR': const Currency(
    code: 'KHR',
    englishName: 'Cambodian Riel',
    precision: 2,
    emoji: '🇰🇭',
  ),
  'KMF': const Currency(
    code: 'KMF',
    englishName: 'Comorian Franc',
    precision: 2,
    emoji: '🇰🇲',
  ),
  'KPW': const Currency(
    code: 'KPW',
    englishName: 'North Korean Won',
    precision: 2,
    emoji: '🇰🇵',
  ),
  'KRW': const Currency(
    code: 'KRW',
    englishName: 'South Korean Won',
    precision: 2,
    emoji: '🇰🇷',
  ),
  'KWD': const Currency(
    code: 'KWD',
    englishName: 'Kuwaiti Dinar',
    precision: 3,
    emoji: '🇰🇼',
  ),
  'KYD': const Currency(
    code: 'KYD',
    englishName: 'Cayman Islands Dollar',
    precision: 2,
    emoji: '🇰🇾',
  ),
  'KZT': const Currency(
    code: 'KZT',
    englishName: 'Kazakhstani Tenge',
    precision: 2,
    emoji: '🇰🇿',
  ),
  'LAK': const Currency(
    code: 'LAK',
    englishName: 'Lao Kip',
    precision: 2,
    emoji: '🇱🇦',
  ),
  'LBP': const Currency(
    code: 'LBP',
    englishName: 'Lebanese Pound',
    precision: 2,
    emoji: '🇱🇧',
  ),
  'LKR': const Currency(
    code: 'LKR',
    englishName: 'Sri Lankan Rupee',
    precision: 2,
    emoji: '🇱🇰',
  ),
  'LRD': const Currency(
    code: 'LRD',
    englishName: 'Liberian Dollar',
    precision: 2,
    emoji: '🇱🇷',
  ),
  'LSL': const Currency(
    code: 'LSL',
    englishName: 'Lesotho Loti',
    precision: 2,
    emoji: '🇱🇸',
  ),
  'LYD': const Currency(
    code: 'LYD',
    englishName: 'Libyan Dinar',
    precision: 3,
    emoji: '🇱🇾',
  ),
  'MAD': const Currency(
    code: 'MAD',
    englishName: 'Moroccan Dirham',
    precision: 2,
    emoji: '🇲🇦',
  ),
  'MDL': const Currency(
    code: 'MDL',
    englishName: 'Moldovan Leu',
    precision: 2,
    emoji: '🇲🇩',
  ),
  'MGA': const Currency(
    code: 'MGA',
    englishName: 'Malagasy Ariary',
    precision: 1,
    emoji: '🇲🇬',
  ),
  'MKD': const Currency(
    code: 'MKD',
    englishName: 'Macedonian Denar',
    precision: 2,
    emoji: '🇲🇰',
  ),
  'MMK': const Currency(
    code: 'MMK',
    englishName: 'Myanmar Kyat',
    precision: 2,
    emoji: '🇲🇲',
  ),
  'MNT': const Currency(
    code: 'MNT',
    englishName: 'Mongolian Tögrög',
    precision: 2,
    emoji: '🇲🇳',
  ),
  'MOP': const Currency(
    code: 'MOP',
    englishName: 'Macanese Pataca',
    precision: 2,
    emoji: '🇲🇴',
  ),
  'MRU': const Currency(
    code: 'MRU',
    englishName: 'Mauritanian Ouguiya',
    precision: 1,
    emoji: '🇲🇷',
  ),
  'MUR': const Currency(
    code: 'MUR',
    englishName: 'Mauritian Rupee',
    precision: 2,
    emoji: '🇲🇺',
  ),
  'MVR': const Currency(
    code: 'MVR',
    englishName: 'Maldivian Rufiyaa',
    precision: 2,
    emoji: '🇲🇻',
  ),
  'MWK': const Currency(
    code: 'MWK',
    englishName: 'Malawian Kwacha',
    precision: 2,
    emoji: '🇲🇼',
  ),
  'MXN': const Currency(
    code: 'MXN',
    englishName: 'Mexican Peso',
    precision: 2,
    emoji: '🇲🇽',
  ),
  'MYR': const Currency(
    code: 'MYR',
    englishName: 'Malaysian Ringgit',
    precision: 2,
    emoji: '🇲🇾',
  ),
  'MZN': const Currency(
    code: 'MZN',
    englishName: 'Mozambican Metical',
    precision: 2,
    emoji: '🇲🇿',
  ),
  'NAD': const Currency(
    code: 'NAD',
    englishName: 'Namibian Dollar',
    precision: 2,
    emoji: '🇳🇦',
  ),
  'NGN': const Currency(
    code: 'NGN',
    englishName: 'Nigerian Naira',
    precision: 2,
    emoji: '🇳🇬',
    symbol: '₦',
  ),
  'NIO': const Currency(
    code: 'NIO',
    englishName: 'Nicaraguan Córdoba',
    precision: 2,
    emoji: '🇳🇮',
  ),
  'NOK': const Currency(
    code: 'NOK',
    englishName: 'Norwegian Krone',
    precision: 2,
    emoji: '🇳🇴',
  ),
  'NPR': const Currency(
    code: 'NPR',
    englishName: 'Nepalese Rupee',
    precision: 2,
    emoji: '🇳🇵',
  ),
  'NZD': const Currency(
    code: 'NZD',
    englishName: 'New Zealand Dollar',
    precision: 2,
    emoji: '🇳🇿',
  ),
  'OMR': const Currency(
    code: 'OMR',
    englishName: 'Omani Rial',
    precision: 3,
    emoji: '🇴🇲',
  ),
  'PAB': const Currency(
    code: 'PAB',
    englishName: 'Panamanian Balboa',
    precision: 2,
    emoji: '🇵🇦',
  ),
  'PEN': const Currency(
    code: 'PEN',
    englishName: 'Peruvian Sol',
    precision: 2,
    emoji: '🇵🇪',
    symbol: 'S/',
  ),
  'PGK': const Currency(
    code: 'PGK',
    englishName: 'Papua New Guinean Kina',
    precision: 2,
    emoji: '🇵🇬',
  ),
  'PHP': const Currency(
    code: 'PHP',
    englishName: 'Philippine Peso',
    precision: 2,
    emoji: '🇵🇭',
    symbol: '₱',
  ),
  'PKR': const Currency(
    code: 'PKR',
    englishName: 'Pakistani Rupee',
    precision: 2,
    emoji: '🇵🇰',
  ),
  'PLN': const Currency(
    code: CurrencyCodes.pln,
    englishName: 'Polish Złoty',
    precision: 2,
    emoji: '🇵🇱',
    symbol: 'zł',
  ),
  'PYG': const Currency(
    code: 'PYG',
    englishName: 'Paraguayan Guaraní',
    precision: 2,
    emoji: '🇵🇾',
    symbol: '₲',
  ),
  'QAR': const Currency(
    code: 'QAR',
    englishName: 'Qatari Riyal',
    precision: 2,
    emoji: '🇶🇦',
    symbol: 'QR',
  ),
  'RON': const Currency(
    code: 'RON',
    englishName: 'Romanian Leu',
    precision: 2,
    emoji: '🇷🇴',
  ),
  'RSD': const Currency(
    code: 'RSD',
    englishName: 'Serbian Dinar',
    precision: 2,
    emoji: '🇷🇸',
  ),
  'RUB': const Currency(
    code: 'RUB',
    englishName: 'Russian Ruble',
    precision: 2,
    emoji: '🇷🇺',
    symbol: '₽',
  ),
  'RWF': const Currency(
    code: 'RWF',
    englishName: 'Rwandan Franc',
    precision: 2,
    emoji: '🇷🇼',
  ),
  'SAR': const Currency(
    code: 'SAR',
    englishName: 'Saudi Riyal',
    precision: 2,
    emoji: '🇸🇦',
  ),
  'SBD': const Currency(
    code: 'SBD',
    englishName: 'Solomon Islands Dollar',
    precision: 2,
    emoji: '🇸🇧',
  ),
  'SCR': const Currency(
    code: 'SCR',
    englishName: 'Seychellois Rupee',
    precision: 2,
    emoji: '🇸🇨',
  ),
  'SDG': const Currency(
    code: 'SDG',
    englishName: 'Sudanese Pound',
    precision: 2,
    emoji: '🇸🇩',
  ),
  'SEK': const Currency(
    code: 'SEK',
    englishName: 'Swedish Krona',
    precision: 2,
    emoji: '🇸🇪',
  ),
  'SGD': const Currency(
    code: CurrencyCodes.sgd,
    englishName: 'Singapore Dollar',
    precision: 1,
    emoji: '🇸🇬',
  ),
  'SHP': const Currency(
    code: 'SHP',
    englishName: 'Saint Helena Pound',
    precision: 2,
    emoji: '🇸🇭',
  ),
  'SLE': const Currency(
    code: 'SLE',
    englishName: 'Sierra Leonean Leone',
    precision: 2,
    emoji: '🇸🇱',
  ),
  'SLL': const Currency(
    code: 'SLL',
    englishName: 'Sierra Leonean Leone',
    precision: 2,
    emoji: '🇸🇱',
  ),
  'SOS': const Currency(
    code: 'SOS',
    englishName: 'Somali Shilling',
    precision: 2,
    emoji: '🇸🇴',
  ),
  'SRD': const Currency(
    code: 'SRD',
    englishName: 'Surinamese Dollar',
    precision: 2,
    emoji: '🇸🇷',
  ),
  'SSP': const Currency(
    code: 'SSP',
    englishName: 'South Sudanese Pound',
    precision: 2,
    emoji: '🇸🇸',
  ),
  'STN': const Currency(
    code: 'STN',
    englishName: 'São Tomé and Príncipe Dobra',
    precision: 2,
    emoji: '🇸🇹',
  ),
  'SVC': const Currency(
    code: 'SVC',
    englishName: 'Salvadoran Colón',
    precision: 2,
    emoji: '🇸🇻',
  ),
  'SYP': const Currency(
    code: 'SYP',
    englishName: 'Syrian Pound',
    precision: 2,
    emoji: '🇸🇾',
  ),
  'SZL': const Currency(
    code: 'SZL',
    englishName: 'Eswatini Lilangeni',
    precision: 2,
    emoji: '🇸🇿',
  ),
  'THB': const Currency(
    code: 'THB',
    englishName: 'Thai Baht',
    precision: 2,
    emoji: '🇹🇭',
    symbol: '฿',
  ),
  'TJS': const Currency(
    code: 'TJS',
    englishName: 'Tajikistani Somoni',
    precision: 2,
    emoji: '🇹🇯',
  ),
  'TMT': const Currency(
    code: 'TMT',
    englishName: 'Turkmenistani Manat',
    precision: 2,
    emoji: '🇹🇲',
  ),
  'TND': const Currency(
    code: 'TND',
    englishName: 'Tunisian Dinar',
    precision: 2,
    emoji: '🇹🇳',
  ),
  'TOP': const Currency(
    code: 'TOP',
    englishName: 'Tongan Paʻanga',
    precision: 2,
    emoji: '🇹🇴',
  ),
  'TRY': const Currency(
    code: 'TRY',
    englishName: 'Turkish Lira',
    precision: 2,
    emoji: '🇹🇷',
    symbol: '₺',
  ),
  'TTD': const Currency(
    code: 'TTD',
    englishName: 'Trinidad and Tobago Dollar',
    precision: 2,
    emoji: '🇹🇹',
  ),
  'TWD': const Currency(
    code: 'TWD',
    englishName: 'New Taiwan Dollar',
    precision: 2,
    emoji: '🇹🇼',
  ),
  'TZS': const Currency(
    code: 'TZS',
    englishName: 'Tanzanian Shilling',
    precision: 2,
    emoji: '🇹🇿',
  ),
  'UAH': const Currency(
    code: 'UAH',
    englishName: 'Ukrainian Hryvnia',
    precision: 2,
    emoji: '🇺🇦',
  ),
  'UGX': const Currency(
    code: 'UGX',
    englishName: 'Ugandan Shilling',
    precision: 2,
    emoji: '🇺🇬',
  ),
  'USD': const Currency(
    code: CurrencyCodes.usd,
    englishName: 'United States Dollar',
    precision: 2,
    emoji: '🇺🇸',
    symbol: '\$',
  ),
  'UYU': const Currency(
    code: 'UYU',
    englishName: 'Uruguayan Peso',
    precision: 2,
    emoji: '🇺🇾',
  ),
  'UZS': const Currency(
    code: 'UZS',
    englishName: 'Uzbekistani Som',
    precision: 2,
    emoji: '🇺🇿',
  ),
  'VED': const Currency(
    code: 'VED',
    englishName: 'Venezuelan Bolívar Digital',
    precision: 2,
    emoji: '🇻🇪',
  ),
  'VES': const Currency(
    code: 'VES',
    englishName: 'Venezuelan Bolívar Soberano',
    precision: 0,
    emoji: '🇻🇪',
  ),
  'VND': const Currency(
    code: 'VND',
    englishName: 'Vietnamese Đồng',
    precision: 2,
    emoji: '🇻🇳',
    symbol: '₫',
  ),
  'VUV': const Currency(
    code: 'VUV',
    englishName: 'Vanuatu Vatu',
    precision: 2,
    emoji: '🇻🇺',
  ),
  'WST': const Currency(
    code: 'WST',
    englishName: 'Samoan Tala',
    precision: 2,
    emoji: '🇼🇸',
  ),
  'XAF': const Currency(
    code: 'XAF',
    englishName: 'Central African CFA Franc',
    precision: 2,
    emoji: '🇨🇲',
  ),
  'XCD': const Currency(
    code: 'XCD',
    englishName: 'East Caribbean Dollar',
    precision: 2,
    emoji: '🇦🇮',
  ),
  'XOF': const Currency(
    code: 'XOF',
    englishName: 'West African CFA Franc',
    precision: 2,
    emoji: '🇧🇯',
  ),
  'XPF': const Currency(
    code: 'XPF',
    englishName: 'CFP Franc',
    precision: 2,
    emoji: '🇵🇫',
  ),
  'YER': const Currency(
    code: 'YER',
    englishName: 'Yemeni Rial',
    precision: 2,
    emoji: '🇾🇪',
  ),
  'ZAR': const Currency(
    code: CurrencyCodes.zar,
    englishName: 'South African Rand',
    precision: 2,
    emoji: '🇿🇦',
  ),
  'ZMW': const Currency(
    code: 'ZMW',
    englishName: 'Zambian Kwacha',
    precision: 2,
    emoji: '🇿🇲',
  ),
};
