part of '../currency.dart';

final Map<String, Currency> _currencyMap = {
  'AED': const Currency(
    code: 'AED',
    englishName: 'United Arab Emirates Dirham',
    precision: 2,
    emojiFlag: '🇦🇪',
    symbol: 'Dh',
    englishCountryNames: {'United Arab Emirates'},
  ),
  'AFN': const Currency(
    code: 'AFN',
    englishName: 'Afghan Afghani',
    precision: 2,
    emojiFlag: '🇦🇫',
    englishCountryNames: {'Afghanistan'},
  ),
  'ALL': const Currency(
    code: 'ALL',
    englishName: 'Albanian Lek',
    precision: 2,
    emojiFlag: '🇦🇱',
    englishCountryNames: {'Albania'},
  ),

  'AMD': const Currency(
    code: 'AMD',
    englishName: 'Armenian Dram',
    precision: 2,
    emojiFlag: '🇦🇲',
    englishCountryNames: {'Armenia'},
  ),
  'ANG': const Currency(
    code: 'ANG',
    englishName: 'Netherlands Antillean Guilder',
    precision: 2,
    emojiFlag: '🇳🇱',
    englishCountryNames: {'Netherlands Antilles'},
  ),
  'AOA': const Currency(
    code: 'AOA',
    englishName: 'Angolan Kwanza',
    precision: 2,
    emojiFlag: '🇦🇴',
    englishCountryNames: {'Angola'},
  ),
  'ARS': const Currency(
    code: 'ARS',
    englishName: 'Argentine Peso',
    precision: 2,
    emojiFlag: '🇦🇷',
    englishCountryNames: {'Argentina'},
  ),
  CurrencyCodes.aud: const Currency(
    code: CurrencyCodes.aud,
    englishName: 'Australian Dollar',
    precision: 2,
    emojiFlag: '🇦🇺',
    englishCountryNames: {'Australia', 'Kiribati', 'Nauru', 'Tuvalu'},
  ),
  'AWG': const Currency(
    code: 'AWG',
    englishName: 'Aruban Florin',
    precision: 2,
    emojiFlag: '🇦🇼',
    englishCountryNames: {'Aruba'},
  ),
  'AZN': const Currency(
    code: 'AZN',
    englishName: 'Azerbaijani Manat',
    precision: 2,
    emojiFlag: '🇦🇿',
    englishCountryNames: {'Azerbaijan'},
  ),
  'BAM': const Currency(
    code: 'BAM',
    englishName: 'Bosnia and Herzegovina Convertible Mark',
    precision: 2,
    emojiFlag: '🇧🇦',
    englishCountryNames: {'Bosnia and Herzegovina'},
  ),
  'BBD': const Currency(
    code: 'BBD',
    englishName: 'Barbadian Dollar',
    precision: 2,
    emojiFlag: '🇧🇧',
    englishCountryNames: {'Barbados'},
  ),
  'BDT': const Currency(
    code: 'BDT',
    englishName: 'Bangladeshi Taka',
    precision: 2,
    emojiFlag: '🇧🇩',
    englishCountryNames: {'Bangladesh'},
  ),
  'BGN': const Currency(
    code: 'BGN',
    englishName: 'Bulgarian Lev',
    precision: 2,
    emojiFlag: '🇧🇬',
    englishCountryNames: {'Bulgaria'},
  ),
  CurrencyCodes.bhd: const Currency(
    code: CurrencyCodes.bhd,
    englishName: 'Bahraini Dinar',
    precision: 3,
    emojiFlag: '🇧🇭',
    englishCountryNames: {'Bahrain'},
  ),
  CurrencyCodes.bif: const Currency(
    code: CurrencyCodes.bif,
    englishName: 'Burundian Franc',
    precision: 2,
    emojiFlag: '🇧🇮',
    englishCountryNames: {'Burundi'},
  ),
  CurrencyCodes.bmd: const Currency(
    code: CurrencyCodes.bmd,
    englishName: 'Bermudian Dollar',
    precision: 2,
    emojiFlag: '🇧🇲',
    englishCountryNames: {'Bermuda'},
  ),
  CurrencyCodes.bnd: const Currency(
    code: CurrencyCodes.bnd,
    englishName: 'Brunei Dollar',
    precision: 1,
    emojiFlag: '🇧🇳',
    englishCountryNames: {'Brunei', 'Singapore'},
  ),
  CurrencyCodes.bob: const Currency(
    code: CurrencyCodes.bob,
    englishName: 'Bolivian Boliviano',
    precision: 2,
    emojiFlag: '🇧🇴',
    englishCountryNames: {'Bolivia'},
  ),
  CurrencyCodes.brl: const Currency(
    code: CurrencyCodes.brl,
    englishName: 'Brazilian Real',
    precision: 2,
    emojiFlag: '🇧🇷',
    englishCountryNames: {'Brazil'},
  ),
  'BSD': const Currency(
    code: 'BSD',
    englishName: 'Bahamian Dollar',
    precision: 2,
    emojiFlag: '🇧🇸',
    englishCountryNames: {'Bahamas'},
  ),
  CurrencyCodes.btc: const Currency(
    code: CurrencyCodes.btc,
    englishName: 'Bitcoin',
    precision: 8,
    englishCountryNames: {'Bitcoin'},
  ),
  'BTN': const Currency(
    code: 'BTN',
    englishName: 'Bhutanese Ngultrum',
    precision: 2,
    emojiFlag: '🇧🇹',
    englishCountryNames: {'Bhutan'},
  ),
  'BWP': const Currency(
    code: 'BWP',
    englishName: 'Botswana Pula',
    precision: 2,
    emojiFlag: '🇧🇼',
    englishCountryNames: {'Botswana'},
  ),
  'BYN': const Currency(
    code: 'BYN',
    englishName: 'Belarusian Ruble',
    precision: 2,
    emojiFlag: '🇧🇾',
    englishCountryNames: {'Belarus'},
  ),
  'BZD': const Currency(
    code: 'BZD',
    englishName: 'Belize Dollar',
    precision: 2,
    emojiFlag: '🇧🇿',
    englishCountryNames: {'Belize'},
  ),
  CurrencyCodes.cad: const Currency(
    code: CurrencyCodes.cad,
    englishName: 'Canadian Dollar',
    precision: 2,
    emojiFlag: '🇨🇦',
    englishCountryNames: {'Canada'},
  ),
  'CDF': const Currency(
    code: 'CDF',
    englishName: 'Congolese Franc',
    precision: 2,
    emojiFlag: '🇨🇩',
    englishCountryNames: {'Democratic Republic of the Congo'},
  ),
  CurrencyCodes.chf: const Currency(
    code: CurrencyCodes.chf,
    englishName: 'Swiss Franc',
    precision: 2,
    emojiFlag: '🇨🇭',
    symbol: 'Fr',
    englishCountryNames: {'Switzerland', 'Liechtenstein'},
  ),
  'CLP': const Currency(
    code: 'CLP',
    englishName: 'Chilean Peso',
    precision: 2,
    emojiFlag: '🇨🇱',
    englishCountryNames: {'Chile'},
  ),
  CurrencyCodes.cny: const Currency(
    code: CurrencyCodes.cny,
    englishName: 'Chinese Yuan',
    precision: 1,
    emojiFlag: '🇨🇳',
    englishCountryNames: {'China'},
  ),
  'COP': const Currency(
    code: 'COP',
    englishName: 'Colombian Peso',
    precision: 2,
    emojiFlag: '🇨🇴',
    englishCountryNames: {'Colombia'},
  ),
  'CRC': const Currency(
    code: 'CRC',
    englishName: 'Costa Rican Colón',
    precision: 2,
    emojiFlag: '🇨🇷',
    englishCountryNames: {'Costa Rica'},
  ),
  'CUP': const Currency(
    code: 'CUP',
    englishName: 'Cuban Peso',
    precision: 2,
    emojiFlag: '🇨🇺',
    englishCountryNames: {'Cuba'},
  ),
  'CVE': const Currency(
    code: 'CVE',
    englishName: 'Cape Verdean Escudo',
    precision: 2,
    emojiFlag: '🇨🇻',
    englishCountryNames: {'Cape Verde'},
  ),
  'CZK': const Currency(
    code: 'CZK',
    englishName: 'Czech Koruna',
    precision: 2,
    emojiFlag: '🇨🇿',
    englishCountryNames: {'Czech Republic'},
  ),
  'DJF': const Currency(
    code: 'DJF',
    englishName: 'Djiboutian Franc',
    precision: 2,
    emojiFlag: '🇩🇯',
    englishCountryNames: {'Djibouti'},
  ),
  'DKK': const Currency(
    code: 'DKK',
    englishName: 'Danish Krone',
    precision: 2,
    emojiFlag: '🇩🇰',
    englishCountryNames: {'Denmark'},
  ),
  'DOP': const Currency(
    code: 'DOP',
    englishName: 'Dominican Peso',
    precision: 2,
    emojiFlag: '🇩🇴',
    englishCountryNames: {'Dominican Republic'},
  ),
  'DZD': const Currency(
    code: 'DZD',
    englishName: 'Algerian Dinar',
    precision: 2,
    emojiFlag: '🇩🇿',
    englishCountryNames: {'Algeria'},
  ),
  'EGP': const Currency(
    code: 'EGP',
    englishName: 'Egyptian Pound',
    precision: 2,
    emojiFlag: '🇪🇬',
    englishCountryNames: {'Egypt'},
  ),
  'ERN': const Currency(
    code: 'ERN',
    englishName: 'Eritrean Nakfa',
    precision: 2,
    emojiFlag: '🇪🇷',
    englishCountryNames: {'Eritrea'},
  ),
  'ETB': const Currency(
    code: 'ETB',
    englishName: 'Ethiopian Birr',
    precision: 2,
    emojiFlag: '🇪🇹',
    englishCountryNames: {'Ethiopia'},
  ),
  CurrencyCodes.eur: const Currency(
    code: CurrencyCodes.eur,
    englishName: 'Euro',
    precision: 2,
    emojiFlag: '🇪🇺',
    symbol: '€',
    englishCountryNames: {
      'European Union',
      'Austria',
      'Belgium',
      'Croatia',
      'Cyprus',
      'Estonia',
      'Finland',
      'France',
      'Germany',
      'Greece',
      'Ireland',
      'Italy',
      'Latvia',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Netherlands',
      'Portugal',
      'Slovakia',
      'Slovenia',
      'Spain',
    },
  ),
  'FJD': const Currency(
    code: 'FJD',
    englishName: 'Fijian Dollar',
    precision: 2,
    emojiFlag: '🇫🇯',
    englishCountryNames: {'Fiji'},
  ),
  'FKP': const Currency(
    code: 'FKP',
    englishName: 'Falkland Islands Pound',
    precision: 2,
    emojiFlag: '🇫🇰',
    englishCountryNames: {'Falkland Islands'},
  ),
  CurrencyCodes.gbp: const Currency(
    code: CurrencyCodes.gbp,
    englishName: 'British Pound Sterling',
    precision: 2,
    emojiFlag: '🇬🇧',
    symbol: '£',
    englishCountryNames: {
      'United Kingdom',
      'British Antarctic Territory',
      'British Indian Ocean Territory',
      'Isle of Man',
      'Jersey',
      'Guernsey',
    },
  ),
  'GEL': const Currency(
    code: 'GEL',
    englishName: 'Georgian Lari',
    precision: 2,
    emojiFlag: '🇬🇪',
    englishCountryNames: {'Georgia'},
  ),
  'GHS': const Currency(
    code: 'GHS',
    englishName: 'Ghanaian Cedi',
    precision: 2,
    emojiFlag: '🇬🇭',
    englishCountryNames: {'Ghana'},
  ),
  'GIP': const Currency(
    code: 'GIP',
    englishName: 'Gibraltar Pound',
    precision: 2,
    emojiFlag: '🇬🇮',
    englishCountryNames: {'Gibraltar'},
  ),
  'GMD': const Currency(
    code: 'GMD',
    englishName: 'Gambian Dalasi',
    precision: 2,
    emojiFlag: '🇬🇲',
    englishCountryNames: {'Gambia'},
  ),
  'GNF': const Currency(
    code: 'GNF',
    englishName: 'Guinean Franc',
    precision: 2,
    emojiFlag: '🇬🇳',
    englishCountryNames: {'Guinea'},
  ),
  'GTQ': const Currency(
    code: 'GTQ',
    englishName: 'Guatemalan Quetzal',
    precision: 2,
    emojiFlag: '🇬🇹',
    englishCountryNames: {'Guatemala'},
  ),
  'GYD': const Currency(
    code: 'GYD',
    englishName: 'Guyanese Dollar',
    precision: 2,
    emojiFlag: '🇬🇾',
    englishCountryNames: {'Guyana'},
  ),
  CurrencyCodes.hkd: const Currency(
    code: CurrencyCodes.hkd,
    englishName: 'Hong Kong Dollar',
    precision: 2,
    emojiFlag: '🇭🇰',
    englishCountryNames: {'Hong Kong'},
  ),
  'HNL': const Currency(
    code: 'HNL',
    englishName: 'Honduran Lempira',
    precision: 2,
    emojiFlag: '🇭🇳',
    englishCountryNames: {'Honduras'},
  ),
  'HTG': const Currency(
    code: 'HTG',
    englishName: 'Haitian Gourde',
    precision: 2,
    emojiFlag: '🇭🇹',
    englishCountryNames: {'Haiti'},
  ),
  'HUF': const Currency(
    code: 'HUF',
    englishName: 'Hungarian Forint',
    precision: 2,
    emojiFlag: '🇭🇺',
    englishCountryNames: {'Hungary'},
  ),
  'IDR': const Currency(
    code: 'IDR',
    englishName: 'Indonesian Rupiah',
    precision: 2,
    emojiFlag: '🇮🇩',
    englishCountryNames: {'Indonesia'},
  ),
  'ILS': const Currency(
    code: 'ILS',
    englishName: 'Israeli New Shekel',
    precision: 2,
    emojiFlag: '🇮🇱',
    symbol: '₪',
    englishCountryNames: {'Israel'},
  ),
  CurrencyCodes.inr: const Currency(
    code: CurrencyCodes.inr,
    englishName: 'Indian Rupee',
    precision: 2,
    emojiFlag: '🇮🇳',
    symbol: '₹',
    englishCountryNames: {'India'},
  ),
  'IQD': const Currency(
    code: 'IQD',
    englishName: 'Iraqi Dinar',
    precision: 3,
    emojiFlag: '🇮🇶',
    englishCountryNames: {'Iraq'},
  ),
  CurrencyCodes.irr: const Currency(
    code: CurrencyCodes.irr,
    englishName: 'Iranian Rial',
    precision: 0,
    emojiFlag: '🇮🇷',
    englishCountryNames: {'Iran'},
  ),
  'ISK': const Currency(
    code: 'ISK',
    englishName: 'Icelandic Króna',
    precision: 2,
    emojiFlag: '🇮🇸',
    englishCountryNames: {'Iceland'},
  ),
  'JMD': const Currency(
    code: 'JMD',
    englishName: 'Jamaican Dollar',
    precision: 2,
    emojiFlag: '🇯🇲',
    englishCountryNames: {'Jamaica'},
  ),
  'JOD': const Currency(
    code: 'JOD',
    englishName: 'Jordanian Dinar',
    precision: 2,
    emojiFlag: '🇯🇴',
    englishCountryNames: {'Jordan'},
  ),
  CurrencyCodes.jpy: const Currency(
    code: CurrencyCodes.jpy,
    englishName: 'Japanese Yen',
    precision: 2,
    emojiFlag: '🇯🇵',
    englishCountryNames: {'Japan'},
  ),
  'KES': const Currency(
    code: 'KES',
    englishName: 'Kenyan Shilling',
    precision: 2,
    emojiFlag: '🇰🇪',
    englishCountryNames: {'Kenya'},
  ),
  'KGS': const Currency(
    code: 'KGS',
    englishName: 'Kyrgyzstani Som',
    precision: 2,
    emojiFlag: '🇰🇬',
    englishCountryNames: {'Kyrgyzstan'},
  ),
  'KHR': const Currency(
    code: 'KHR',
    englishName: 'Cambodian Riel',
    precision: 2,
    emojiFlag: '🇰🇭',
    englishCountryNames: {'Cambodia'},
  ),
  'KMF': const Currency(
    code: 'KMF',
    englishName: 'Comorian Franc',
    precision: 2,
    emojiFlag: '🇰🇲',
    englishCountryNames: {'Comoros'},
  ),
  'KPW': const Currency(
    code: 'KPW',
    englishName: 'North Korean Won',
    precision: 2,
    emojiFlag: '🇰🇵',
    englishCountryNames: {'North Korea'},
  ),
  'KRW': const Currency(
    code: 'KRW',
    englishName: 'South Korean Won',
    precision: 2,
    emojiFlag: '🇰🇷',
    englishCountryNames: {'South Korea'},
  ),
  'KWD': const Currency(
    code: 'KWD',
    englishName: 'Kuwaiti Dinar',
    precision: 3,
    emojiFlag: '🇰🇼',
    englishCountryNames: {'Kuwait'},
  ),
  'KYD': const Currency(
    code: 'KYD',
    englishName: 'Cayman Islands Dollar',
    precision: 2,
    emojiFlag: '🇰🇾',
    englishCountryNames: {'Cayman Islands'},
  ),
  'KZT': const Currency(
    code: 'KZT',
    englishName: 'Kazakhstani Tenge',
    precision: 2,
    emojiFlag: '🇰🇿',
    englishCountryNames: {'Kazakhstan'},
  ),
  'LAK': const Currency(
    code: 'LAK',
    englishName: 'Lao Kip',
    precision: 2,
    emojiFlag: '🇱🇦',
    englishCountryNames: {'Laos'},
  ),
  'LBP': const Currency(
    code: 'LBP',
    englishName: 'Lebanese Pound',
    precision: 2,
    emojiFlag: '🇱🇧',
    englishCountryNames: {'Lebanon'},
  ),
  'LKR': const Currency(
    code: 'LKR',
    englishName: 'Sri Lankan Rupee',
    precision: 2,
    emojiFlag: '🇱🇰',
    englishCountryNames: {'Sri Lanka'},
  ),
  'LRD': const Currency(
    code: 'LRD',
    englishName: 'Liberian Dollar',
    precision: 2,
    emojiFlag: '🇱🇷',
    englishCountryNames: {'Liberia'},
  ),
  'LSL': const Currency(
    code: 'LSL',
    englishName: 'Lesotho Loti',
    precision: 2,
    emojiFlag: '🇱🇸',
    englishCountryNames: {'Lesotho'},
  ),
  'LYD': const Currency(
    code: 'LYD',
    englishName: 'Libyan Dinar',
    precision: 3,
    emojiFlag: '🇱🇾',
    englishCountryNames: {'Libya'},
  ),
  'MAD': const Currency(
    code: 'MAD',
    englishName: 'Moroccan Dirham',
    precision: 2,
    emojiFlag: '🇲🇦',
    englishCountryNames: {'Morocco'},
  ),
  'MDL': const Currency(
    code: 'MDL',
    englishName: 'Moldovan Leu',
    precision: 2,
    emojiFlag: '🇲🇩',
    englishCountryNames: {'Moldova'},
  ),
  'MGA': const Currency(
    code: 'MGA',
    englishName: 'Malagasy Ariary',
    precision: 1,
    emojiFlag: '🇲🇬',
    englishCountryNames: {'Madagascar'},
  ),
  'MKD': const Currency(
    code: 'MKD',
    englishName: 'Macedonian Denar',
    precision: 2,
    emojiFlag: '🇲🇰',
    englishCountryNames: {'North Macedonia'},
  ),
  'MMK': const Currency(
    code: 'MMK',
    englishName: 'Myanmar Kyat',
    precision: 2,
    emojiFlag: '🇲🇲',
    englishCountryNames: {'Myanmar'},
  ),
  'MNT': const Currency(
    code: 'MNT',
    englishName: 'Mongolian Tögrög',
    precision: 2,
    emojiFlag: '🇲🇳',
    englishCountryNames: {'Mongolia'},
  ),
  'MOP': const Currency(
    code: 'MOP',
    englishName: 'Macanese Pataca',
    precision: 2,
    emojiFlag: '🇲🇴',
    englishCountryNames: {'Macau'},
  ),
  'MRU': const Currency(
    code: 'MRU',
    englishName: 'Mauritanian Ouguiya',
    precision: 1,
    emojiFlag: '🇲🇷',
    englishCountryNames: {'Mauritania'},
  ),
  'MUR': const Currency(
    code: 'MUR',
    englishName: 'Mauritian Rupee',
    precision: 2,
    emojiFlag: '🇲🇺',
    englishCountryNames: {'Mauritius'},
  ),
  'MVR': const Currency(
    code: 'MVR',
    englishName: 'Maldivian Rufiyaa',
    precision: 2,
    emojiFlag: '🇲🇻',
    englishCountryNames: {'Maldives'},
  ),
  'MWK': const Currency(
    code: 'MWK',
    englishName: 'Malawian Kwacha',
    precision: 2,
    emojiFlag: '🇲🇼',
    englishCountryNames: {'Malawi'},
  ),
  'MXN': const Currency(
    code: 'MXN',
    englishName: 'Mexican Peso',
    precision: 2,
    emojiFlag: '🇲🇽',
    englishCountryNames: {'Mexico'},
  ),
  'MYR': const Currency(
    code: 'MYR',
    englishName: 'Malaysian Ringgit',
    precision: 2,
    emojiFlag: '🇲🇾',
    englishCountryNames: {'Malaysia'},
  ),
  'MZN': const Currency(
    code: 'MZN',
    englishName: 'Mozambican Metical',
    precision: 2,
    emojiFlag: '🇲🇿',
    englishCountryNames: {'Mozambique'},
  ),
  'NAD': const Currency(
    code: 'NAD',
    englishName: 'Namibian Dollar',
    precision: 2,
    emojiFlag: '🇳🇦',
    englishCountryNames: {'Namibia'},
  ),
  'NGN': const Currency(
    code: 'NGN',
    englishName: 'Nigerian Naira',
    precision: 2,
    emojiFlag: '🇳🇬',
    symbol: '₦',
    englishCountryNames: {'Nigeria'},
  ),
  'NIO': const Currency(
    code: 'NIO',
    englishName: 'Nicaraguan Córdoba',
    precision: 2,
    emojiFlag: '🇳🇮',
    englishCountryNames: {'Nicaragua'},
  ),
  'NOK': const Currency(
    code: 'NOK',
    englishName: 'Norwegian Krone',
    precision: 2,
    emojiFlag: '🇳🇴',
    englishCountryNames: {'Norway'},
  ),
  'NPR': const Currency(
    code: 'NPR',
    englishName: 'Nepalese Rupee',
    precision: 2,
    emojiFlag: '🇳🇵',
    englishCountryNames: {'Nepal'},
  ),
  'NZD': const Currency(
    code: 'NZD',
    englishName: 'New Zealand Dollar',
    precision: 2,
    emojiFlag: '🇳🇿',
    englishCountryNames: {'New Zealand', 'Cook Islands', 'Niue', 'Pitcairn Islands', 'Tokelau'},
  ),
  'OMR': const Currency(
    code: 'OMR',
    englishName: 'Omani Rial',
    precision: 3,
    emojiFlag: '🇴🇲',
    englishCountryNames: {'Oman'},
  ),
  'PAB': const Currency(
    code: 'PAB',
    englishName: 'Panamanian Balboa',
    precision: 2,
    emojiFlag: '🇵🇦',
    englishCountryNames: {'Panama'},
  ),
  'PEN': const Currency(
    code: 'PEN',
    englishName: 'Peruvian Sol',
    precision: 2,
    emojiFlag: '🇵🇪',
    symbol: 'S/',
    englishCountryNames: {'Peru'},
  ),
  'PGK': const Currency(
    code: 'PGK',
    englishName: 'Papua New Guinean Kina',
    precision: 2,
    emojiFlag: '🇵🇬',
    englishCountryNames: {'Papua New Guinea'},
  ),
  'PHP': const Currency(
    code: 'PHP',
    englishName: 'Philippine Peso',
    precision: 2,
    emojiFlag: '🇵🇭',
    symbol: '₱',
    englishCountryNames: {'Philippines'},
  ),
  'PKR': const Currency(
    code: 'PKR',
    englishName: 'Pakistani Rupee',
    precision: 2,
    emojiFlag: '🇵🇰',
    englishCountryNames: {'Pakistan'},
  ),
  CurrencyCodes.pln: const Currency(
    code: CurrencyCodes.pln,
    englishName: 'Polish Złoty',
    precision: 2,
    emojiFlag: '🇵🇱',
    symbol: 'zł',
    englishCountryNames: {'Poland'},
  ),
  'PYG': const Currency(
    code: 'PYG',
    englishName: 'Paraguayan Guaraní',
    precision: 2,
    emojiFlag: '🇵🇾',
    symbol: '₲',
    englishCountryNames: {'Paraguay'},
  ),
  'QAR': const Currency(
    code: 'QAR',
    englishName: 'Qatari Riyal',
    precision: 2,
    emojiFlag: '🇶🇦',
    symbol: 'QR',
    englishCountryNames: {'Qatar'},
  ),
  'RON': const Currency(
    code: 'RON',
    englishName: 'Romanian Leu',
    precision: 2,
    emojiFlag: '🇷🇴',
    englishCountryNames: {'Romania'},
  ),
  'RSD': const Currency(
    code: 'RSD',
    englishName: 'Serbian Dinar',
    precision: 2,
    emojiFlag: '🇷🇸',
    englishCountryNames: {'Serbia'},
  ),
  'RUB': const Currency(
    code: 'RUB',
    englishName: 'Russian Ruble',
    precision: 2,
    emojiFlag: '🇷🇺',
    symbol: '₽',
    englishCountryNames: {'Russia'},
  ),
  'RWF': const Currency(
    code: 'RWF',
    englishName: 'Rwandan Franc',
    precision: 2,
    emojiFlag: '🇷🇼',
    englishCountryNames: {'Rwanda'},
  ),
  'SAR': const Currency(
    code: 'SAR',
    englishName: 'Saudi Riyal',
    precision: 2,
    emojiFlag: '🇸🇦',
    englishCountryNames: {'Saudi Arabia'},
  ),
  'SBD': const Currency(
    code: 'SBD',
    englishName: 'Solomon Islands Dollar',
    precision: 2,
    emojiFlag: '🇸🇧',
    englishCountryNames: {'Solomon Islands'},
  ),
  'SCR': const Currency(
    code: 'SCR',
    englishName: 'Seychellois Rupee',
    precision: 2,
    emojiFlag: '🇸🇨',
    englishCountryNames: {'Seychelles'},
  ),
  'SDG': const Currency(
    code: 'SDG',
    englishName: 'Sudanese Pound',
    precision: 2,
    emojiFlag: '🇸🇩',
    englishCountryNames: {'Sudan'},
  ),
  'SEK': const Currency(
    code: 'SEK',
    englishName: 'Swedish Krona',
    precision: 2,
    emojiFlag: '🇸🇪',
    englishCountryNames: {'Sweden'},
  ),
  CurrencyCodes.sgd: const Currency(
    code: CurrencyCodes.sgd,
    englishName: 'Singapore Dollar',
    precision: 1,
    emojiFlag: '🇸🇬',
    englishCountryNames: {'Singapore', 'Brunei'},
  ),
  'SHP': const Currency(
    code: 'SHP',
    englishName: 'Saint Helena Pound',
    precision: 2,
    emojiFlag: '🇸🇭',
    englishCountryNames: {'Saint Helena'},
  ),
  'SLE': const Currency(
    code: 'SLE',
    englishName: 'Sierra Leonean Leone',
    precision: 2,
    emojiFlag: '🇸🇱',
    englishCountryNames: {'Sierra Leone'},
  ),
  'SOS': const Currency(
    code: 'SOS',
    englishName: 'Somali Shilling',
    precision: 2,
    emojiFlag: '🇸🇴',
    englishCountryNames: {'Somalia'},
  ),
  'SRD': const Currency(
    code: 'SRD',
    englishName: 'Surinamese Dollar',
    precision: 2,
    emojiFlag: '🇸🇷',
    englishCountryNames: {'Suriname'},
  ),
  'SSP': const Currency(
    code: 'SSP',
    englishName: 'South Sudanese Pound',
    precision: 2,
    emojiFlag: '🇸🇸',
    englishCountryNames: {'South Sudan'},
  ),
  'STN': const Currency(
    code: 'STN',
    englishName: 'São Tomé and Príncipe Dobra',
    precision: 2,
    emojiFlag: '🇸🇹',
    englishCountryNames: {'São Tomé and Príncipe'},
  ),
  'SVC': const Currency(
    code: 'SVC',
    englishName: 'Salvadoran Colón',
    precision: 2,
    emojiFlag: '🇸🇻',
    englishCountryNames: {'El Salvador'},
  ),
  'SYP': const Currency(
    code: 'SYP',
    englishName: 'Syrian Pound',
    precision: 2,
    emojiFlag: '🇸🇾',
    englishCountryNames: {'Syria'},
  ),
  'SZL': const Currency(
    code: 'SZL',
    englishName: 'Eswatini Lilangeni',
    precision: 2,
    emojiFlag: '🇸🇿',
    englishCountryNames: {'Eswatini'},
  ),
  'THB': const Currency(
    code: 'THB',
    englishName: 'Thai Baht',
    precision: 2,
    emojiFlag: '🇹🇭',
    symbol: '฿',
    englishCountryNames: {'Thailand'},
  ),
  'TJS': const Currency(
    code: 'TJS',
    englishName: 'Tajikistani Somoni',
    precision: 2,
    emojiFlag: '🇹🇯',
    englishCountryNames: {'Tajikistan'},
  ),
  'TMT': const Currency(
    code: 'TMT',
    englishName: 'Turkmenistani Manat',
    precision: 2,
    emojiFlag: '🇹🇲',
    englishCountryNames: {'Turkmenistan'},
  ),
  'TND': const Currency(
    code: 'TND',
    englishName: 'Tunisian Dinar',
    precision: 3,
    emojiFlag: '🇹🇳',
    englishCountryNames: {'Tunisia'},
  ),
  'TOP': const Currency(
    code: 'TOP',
    englishName: 'Tongan Paʻanga',
    precision: 2,
    emojiFlag: '🇹🇴',
    englishCountryNames: {'Tonga'},
  ),
  'TRY': const Currency(
    code: 'TRY',
    englishName: 'Turkish Lira',
    precision: 2,
    emojiFlag: '🇹🇷',
    symbol: '₺',
    englishCountryNames: {'Turkey'},
  ),
  'TTD': const Currency(
    code: 'TTD',
    englishName: 'Trinidad and Tobago Dollar',
    precision: 2,
    emojiFlag: '🇹🇹',
    englishCountryNames: {'Trinidad and Tobago'},
  ),
  'TWD': const Currency(
    code: 'TWD',
    englishName: 'New Taiwan Dollar',
    precision: 2,
    emojiFlag: '🇹🇼',
    englishCountryNames: {'Taiwan'},
  ),
  'TZS': const Currency(
    code: 'TZS',
    englishName: 'Tanzanian Shilling',
    precision: 2,
    emojiFlag: '🇹🇿',
    englishCountryNames: {'Tanzania'},
  ),
  'UAH': const Currency(
    code: 'UAH',
    englishName: 'Ukrainian Hryvnia',
    precision: 2,
    emojiFlag: '🇺🇦',
    englishCountryNames: {'Ukraine'},
  ),
  'UGX': const Currency(
    code: 'UGX',
    englishName: 'Ugandan Shilling',
    precision: 2,
    emojiFlag: '🇺🇬',
    englishCountryNames: {'Uganda'},
  ),
  CurrencyCodes.usd: const Currency(
    code: CurrencyCodes.usd,
    englishName: 'United States Dollar',
    precision: 2,
    emojiFlag: '🇺🇸',
    symbol: '\$',
    englishCountryNames: {
      'United States',
      'Ecuador',
      'El Salvador',
      'Panama',
      'East Timor',
      'Zimbabwe',
      'Micronesia',
      'Palau',
      'Marshall Islands',
      'Caribbean Netherlands',
      'Turks and Caicos Islands',
      'British Virgin Islands',
    },
  ),
  'UYU': const Currency(
    code: 'UYU',
    englishName: 'Uruguayan Peso',
    precision: 2,
    emojiFlag: '🇺🇾',
    englishCountryNames: {'Uruguay'},
  ),
  'UZS': const Currency(
    code: 'UZS',
    englishName: 'Uzbekistani Som',
    precision: 2,
    emojiFlag: '🇺🇿',
    englishCountryNames: {'Uzbekistan'},
  ),
  'VED': const Currency(
    code: 'VED',
    englishName: 'Venezuelan Bolívar Digital',
    precision: 2,
    emojiFlag: '🇻🇪',
    englishCountryNames: {'Venezuela'},
  ),
  'VES': const Currency(
    code: 'VES',
    englishName: 'Venezuelan Bolívar Soberano',
    precision: 0,
    emojiFlag: '🇻🇪',
    englishCountryNames: {'Venezuela'},
  ),
  'VND': const Currency(
    code: 'VND',
    englishName: 'Vietnamese Đồng',
    precision: 2,
    emojiFlag: '🇻🇳',
    symbol: '₫',
    englishCountryNames: {'Vietnam'},
  ),
  'VUV': const Currency(
    code: 'VUV',
    englishName: 'Vanuatu Vatu',
    precision: 2,
    emojiFlag: '🇻🇺',
    englishCountryNames: {'Vanuatu'},
  ),
  'WST': const Currency(
    code: 'WST',
    englishName: 'Samoan Tala',
    precision: 2,
    emojiFlag: '🇼🇸',
    englishCountryNames: {'Samoa'},
  ),
  'XAF': const Currency(
    code: 'XAF',
    englishName: 'Central African CFA Franc',
    precision: 2,
    emojiFlag: '🇨🇲',
    englishCountryNames: {
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Republic of the Congo',
      'Equatorial Guinea',
      'Gabon',
    },
  ),
  'XCD': const Currency(
    code: 'XCD',
    englishName: 'East Caribbean Dollar',
    precision: 2,
    emojiFlag: '🇦🇮',
    englishCountryNames: {
      'Anguilla',
      'Antigua and Barbuda',
      'Dominica',
      'Grenada',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
      'Montserrat',
    },
  ),
  'XOF': const Currency(
    code: 'XOF',
    englishName: 'West African CFA Franc',
    precision: 2,
    emojiFlag: '🇧🇯',
    englishCountryNames: {
      'Benin',
      'Burkina Faso',
      "Côte d'Ivoire",
      'Guinea-Bissau',
      'Mali',
      'Niger',
      'Senegal',
      'Togo',
    },
  ),
  'XPF': const Currency(
    code: 'XPF',
    englishName: 'CFP Franc',
    precision: 2,
    emojiFlag: '🇵🇫',
    englishCountryNames: {'French Polynesia', 'New Caledonia', 'Wallis and Futuna'},
  ),
  'YER': const Currency(
    code: 'YER',
    englishName: 'Yemeni Rial',
    precision: 2,
    emojiFlag: '🇾🇪',
    englishCountryNames: {'Yemen'},
  ),
  CurrencyCodes.zar: const Currency(
    code: CurrencyCodes.zar,
    englishName: 'South African Rand',
    precision: 2,
    emojiFlag: '🇿🇦',
    englishCountryNames: {'South Africa'},
  ),
  'ZMW': const Currency(
    code: 'ZMW',
    englishName: 'Zambian Kwacha',
    precision: 2,
    emojiFlag: '🇿🇲',
    englishCountryNames: {'Zambia'},
  ),
};
