part of '../currency.dart';

final Map<String, Currency> _currencyMap = {
  CurrencyCodes.aed: const Currency(
    code: CurrencyCodes.aed,
    englishName: 'United Arab Emirates Dirham',
    precision: 2,
    emojiFlag: '🇦🇪',
    symbol: 'Dh',
    englishCountryNames: {'United Arab Emirates'},
  ),
  CurrencyCodes.afn: const Currency(
    code: CurrencyCodes.afn,
    englishName: 'Afghan Afghani',
    precision: 2,
    emojiFlag: '🇦🇫',
    englishCountryNames: {'Afghanistan'},
  ),
  CurrencyCodes.all: const Currency(
    code: CurrencyCodes.all,
    englishName: 'Albanian Lek',
    precision: 2,
    emojiFlag: '🇦🇱',
    englishCountryNames: {'Albania'},
  ),
  CurrencyCodes.amd: const Currency(
    code: CurrencyCodes.amd,
    englishName: 'Armenian Dram',
    precision: 2,
    emojiFlag: '🇦🇲',
    englishCountryNames: {'Armenia'},
  ),
  CurrencyCodes.ang: const Currency(
    code: CurrencyCodes.ang,
    englishName: 'Netherlands Antillean Guilder',
    precision: 2,
    emojiFlag: '🇳🇱',
    englishCountryNames: {'Netherlands Antilles'},
  ),
  CurrencyCodes.aoa: const Currency(
    code: CurrencyCodes.aoa,
    englishName: 'Angolan Kwanza',
    precision: 2,
    emojiFlag: '🇦🇴',
    englishCountryNames: {'Angola'},
  ),
  CurrencyCodes.ars: const Currency(
    code: CurrencyCodes.ars,
    englishName: 'Argentine Peso',
    precision: 2,
    emojiFlag: '🇦🇷',
    englishCountryNames: {'Argentina'},
  ),
  CurrencyCodes.aud: const Currency(
    code: CurrencyCodes.aud,
    englishName: 'Australian Dollar',
    precision: 2,
    emojiFlag: '🇦🇺',
    englishCountryNames: {'Australia', 'Kiribati', 'Nauru', 'Tuvalu'},
  ),
  CurrencyCodes.awg: const Currency(
    code: CurrencyCodes.awg,
    englishName: 'Aruban Florin',
    precision: 2,
    emojiFlag: '🇦🇼',
    englishCountryNames: {'Aruba'},
  ),
  CurrencyCodes.azn: const Currency(
    code: CurrencyCodes.azn,
    englishName: 'Azerbaijani Manat',
    precision: 2,
    emojiFlag: '🇦🇿',
    englishCountryNames: {'Azerbaijan'},
  ),
  CurrencyCodes.bam: const Currency(
    code: CurrencyCodes.bam,
    englishName: 'Bosnia and Herzegovina Convertible Mark',
    precision: 2,
    emojiFlag: '🇧🇦',
    englishCountryNames: {'Bosnia and Herzegovina'},
  ),
  CurrencyCodes.bbd: const Currency(
    code: CurrencyCodes.bbd,
    englishName: 'Barbadian Dollar',
    precision: 2,
    emojiFlag: '🇧🇧',
    englishCountryNames: {'Barbados'},
  ),
  CurrencyCodes.bdt: const Currency(
    code: CurrencyCodes.bdt,
    englishName: 'Bangladeshi Taka',
    precision: 2,
    emojiFlag: '🇧🇩',
    englishCountryNames: {'Bangladesh'},
  ),
  CurrencyCodes.bgn: const Currency(
    code: CurrencyCodes.bgn,
    englishName: 'Bulgarian Lev',
    precision: 2,
    emojiFlag: '🇧🇬',
    englishCountryNames: {'Bulgaria'},
  ),
  CurrencyCodes.bhd: const Currency(
    code: CurrencyCodes.bhd,
    englishName: 'Bahraini Dinar',
    precision: 3,
    emojiFlag: '🇧🇭',
    englishCountryNames: {'Bahrain'},
  ),
  CurrencyCodes.bif: const Currency(
    code: CurrencyCodes.bif,
    englishName: 'Burundian Franc',
    precision: 2,
    emojiFlag: '🇧🇮',
    englishCountryNames: {'Burundi'},
  ),
  CurrencyCodes.bmd: const Currency(
    code: CurrencyCodes.bmd,
    englishName: 'Bermudian Dollar',
    precision: 2,
    emojiFlag: '🇧🇲',
    englishCountryNames: {'Bermuda'},
  ),
  CurrencyCodes.bnd: const Currency(
    code: CurrencyCodes.bnd,
    englishName: 'Brunei Dollar',
    precision: 1,
    emojiFlag: '🇧🇳',
    englishCountryNames: {'Brunei', 'Singapore'},
  ),
  CurrencyCodes.bob: const Currency(
    code: CurrencyCodes.bob,
    englishName: 'Bolivian Boliviano',
    precision: 2,
    emojiFlag: '🇧🇴',
    englishCountryNames: {'Bolivia'},
  ),
  CurrencyCodes.brl: const Currency(
    code: CurrencyCodes.brl,
    englishName: 'Brazilian Real',
    precision: 2,
    emojiFlag: '🇧🇷',
    englishCountryNames: {'Brazil'},
  ),
  CurrencyCodes.bsd: const Currency(
    code: CurrencyCodes.bsd,
    englishName: 'Bahamian Dollar',
    precision: 2,
    emojiFlag: '🇧🇸',
    englishCountryNames: {'Bahamas'},
  ),
  CurrencyCodes.btc: const Currency(
    code: CurrencyCodes.btc,
    englishName: 'Bitcoin',
    precision: 8,
    englishCountryNames: {'Bitcoin'},
  ),
  CurrencyCodes.btn: const Currency(
    code: CurrencyCodes.btn,
    englishName: 'Bhutanese Ngultrum',
    precision: 2,
    emojiFlag: '🇧🇹',
    englishCountryNames: {'Bhutan'},
  ),
  CurrencyCodes.bwp: const Currency(
    code: CurrencyCodes.bwp,
    englishName: 'Botswana Pula',
    precision: 2,
    emojiFlag: '🇧🇼',
    englishCountryNames: {'Botswana'},
  ),
  CurrencyCodes.byn: const Currency(
    code: CurrencyCodes.byn,
    englishName: 'Belarusian Ruble',
    precision: 2,
    emojiFlag: '🇧🇾',
    englishCountryNames: {'Belarus'},
  ),
  CurrencyCodes.bzd: const Currency(
    code: CurrencyCodes.bzd,
    englishName: 'Belize Dollar',
    precision: 2,
    emojiFlag: '🇧🇿',
    englishCountryNames: {'Belize'},
  ),
  CurrencyCodes.cad: const Currency(
    code: CurrencyCodes.cad,
    englishName: 'Canadian Dollar',
    precision: 2,
    emojiFlag: '🇨🇦',
    englishCountryNames: {'Canada'},
  ),
  CurrencyCodes.cdf: const Currency(
    code: CurrencyCodes.cdf,
    englishName: 'Congolese Franc',
    precision: 2,
    emojiFlag: '🇨🇩',
    englishCountryNames: {'Democratic Republic of the Congo'},
  ),
  CurrencyCodes.chf: const Currency(
    code: CurrencyCodes.chf,
    englishName: 'Swiss Franc',
    precision: 2,
    emojiFlag: '🇨🇭',
    symbol: 'Fr',
    englishCountryNames: {'Switzerland', 'Liechtenstein'},
  ),
  CurrencyCodes.clp: const Currency(
    code: CurrencyCodes.clp,
    englishName: 'Chilean Peso',
    precision: 2,
    emojiFlag: '🇨🇱',
    englishCountryNames: {'Chile'},
  ),
  CurrencyCodes.cny: const Currency(
    code: CurrencyCodes.cny,
    englishName: 'Chinese Yuan',
    precision: 1,
    emojiFlag: '🇨🇳',
    englishCountryNames: {'China'},
  ),
  CurrencyCodes.cop: const Currency(
    code: CurrencyCodes.cop,
    englishName: 'Colombian Peso',
    precision: 2,
    emojiFlag: '🇨🇴',
    englishCountryNames: {'Colombia'},
  ),
  CurrencyCodes.crc: const Currency(
    code: CurrencyCodes.crc,
    englishName: 'Costa Rican Colón',
    precision: 2,
    emojiFlag: '🇨🇷',
    englishCountryNames: {'Costa Rica'},
  ),
  CurrencyCodes.cup: const Currency(
    code: CurrencyCodes.cup,
    englishName: 'Cuban Peso',
    precision: 2,
    emojiFlag: '🇨🇺',
    englishCountryNames: {'Cuba'},
  ),
  CurrencyCodes.cve: const Currency(
    code: CurrencyCodes.cve,
    englishName: 'Cape Verdean Escudo',
    precision: 2,
    emojiFlag: '🇨🇻',
    englishCountryNames: {'Cape Verde'},
  ),
  CurrencyCodes.czk: const Currency(
    code: CurrencyCodes.czk,
    englishName: 'Czech Koruna',
    precision: 2,
    emojiFlag: '🇨🇿',
    englishCountryNames: {'Czech Republic'},
  ),
  CurrencyCodes.djf: const Currency(
    code: CurrencyCodes.djf,
    englishName: 'Djiboutian Franc',
    precision: 2,
    emojiFlag: '🇩🇯',
    englishCountryNames: {'Djibouti'},
  ),
  CurrencyCodes.dkk: const Currency(
    code: CurrencyCodes.dkk,
    englishName: 'Danish Krone',
    precision: 2,
    emojiFlag: '🇩🇰',
    englishCountryNames: {'Denmark'},
  ),
  CurrencyCodes.dop: const Currency(
    code: CurrencyCodes.dop,
    englishName: 'Dominican Peso',
    precision: 2,
    emojiFlag: '🇩🇴',
    englishCountryNames: {'Dominican Republic'},
  ),
  CurrencyCodes.dzd: const Currency(
    code: CurrencyCodes.dzd,
    englishName: 'Algerian Dinar',
    precision: 2,
    emojiFlag: '🇩🇿',
    englishCountryNames: {'Algeria'},
  ),
  CurrencyCodes.egp: const Currency(
    code: CurrencyCodes.egp,
    englishName: 'Egyptian Pound',
    precision: 2,
    emojiFlag: '🇪🇬',
    englishCountryNames: {'Egypt'},
  ),
  CurrencyCodes.ern: const Currency(
    code: CurrencyCodes.ern,
    englishName: 'Eritrean Nakfa',
    precision: 2,
    emojiFlag: '🇪🇷',
    englishCountryNames: {'Eritrea'},
  ),
  CurrencyCodes.etb: const Currency(
    code: CurrencyCodes.etb,
    englishName: 'Ethiopian Birr',
    precision: 2,
    emojiFlag: '🇪🇹',
    englishCountryNames: {'Ethiopia'},
  ),
  CurrencyCodes.eur: const Currency(
    code: CurrencyCodes.eur,
    englishName: 'Euro',
    precision: 2,
    emojiFlag: '🇪🇺',
    symbol: '€',
    englishCountryNames: {
      'European Union',
      'Austria',
      'Belgium',
      'Croatia',
      'Cyprus',
      'Estonia',
      'Finland',
      'France',
      'Germany',
      'Greece',
      'Ireland',
      'Italy',
      'Latvia',
      'Lithuania',
      'Luxembourg',
      'Malta',
      'Netherlands',
      'Portugal',
      'Slovakia',
      'Slovenia',
      'Spain',
    },
  ),
  CurrencyCodes.fjd: const Currency(
    code: CurrencyCodes.fjd,
    englishName: 'Fijian Dollar',
    precision: 2,
    emojiFlag: '🇫🇯',
    englishCountryNames: {'Fiji'},
  ),
  CurrencyCodes.fkp: const Currency(
    code: CurrencyCodes.fkp,
    englishName: 'Falkland Islands Pound',
    precision: 2,
    emojiFlag: '🇫🇰',
    englishCountryNames: {'Falkland Islands'},
  ),
  CurrencyCodes.gbp: const Currency(
    code: CurrencyCodes.gbp,
    englishName: 'British Pound Sterling',
    precision: 2,
    emojiFlag: '🇬🇧',
    symbol: '£',
    englishCountryNames: {
      'United Kingdom',
      'British Antarctic Territory',
      'British Indian Ocean Territory',
      'Isle of Man',
      'Jersey',
      'Guernsey',
    },
  ),
  CurrencyCodes.gel: const Currency(
    code: CurrencyCodes.gel,
    englishName: 'Georgian Lari',
    precision: 2,
    emojiFlag: '🇬🇪',
    englishCountryNames: {'Georgia'},
  ),
  CurrencyCodes.ghs: const Currency(
    code: CurrencyCodes.ghs,
    englishName: 'Ghanaian Cedi',
    precision: 2,
    emojiFlag: '🇬🇭',
    englishCountryNames: {'Ghana'},
  ),
  CurrencyCodes.gip: const Currency(
    code: CurrencyCodes.gip,
    englishName: 'Gibraltar Pound',
    precision: 2,
    emojiFlag: '🇬🇮',
    englishCountryNames: {'Gibraltar'},
  ),
  CurrencyCodes.gmd: const Currency(
    code: CurrencyCodes.gmd,
    englishName: 'Gambian Dalasi',
    precision: 2,
    emojiFlag: '🇬🇲',
    englishCountryNames: {'Gambia'},
  ),
  CurrencyCodes.gnf: const Currency(
    code: CurrencyCodes.gnf,
    englishName: 'Guinean Franc',
    precision: 2,
    emojiFlag: '🇬🇳',
    englishCountryNames: {'Guinea'},
  ),
  CurrencyCodes.gtq: const Currency(
    code: CurrencyCodes.gtq,
    englishName: 'Guatemalan Quetzal',
    precision: 2,
    emojiFlag: '🇬🇹',
    englishCountryNames: {'Guatemala'},
  ),
  CurrencyCodes.gyd: const Currency(
    code: CurrencyCodes.gyd,
    englishName: 'Guyanese Dollar',
    precision: 2,
    emojiFlag: '🇬🇾',
    englishCountryNames: {'Guyana'},
  ),
  CurrencyCodes.hkd: const Currency(
    code: CurrencyCodes.hkd,
    englishName: 'Hong Kong Dollar',
    precision: 2,
    emojiFlag: '🇭🇰',
    englishCountryNames: {'Hong Kong'},
  ),
  CurrencyCodes.hnl: const Currency(
    code: CurrencyCodes.hnl,
    englishName: 'Honduran Lempira',
    precision: 2,
    emojiFlag: '🇭🇳',
    englishCountryNames: {'Honduras'},
  ),
  CurrencyCodes.htg: const Currency(
    code: CurrencyCodes.htg,
    englishName: 'Haitian Gourde',
    precision: 2,
    emojiFlag: '🇭🇹',
    englishCountryNames: {'Haiti'},
  ),
  CurrencyCodes.huf: const Currency(
    code: CurrencyCodes.huf,
    englishName: 'Hungarian Forint',
    precision: 2,
    emojiFlag: '🇭🇺',
    englishCountryNames: {'Hungary'},
  ),
  CurrencyCodes.idr: const Currency(
    code: CurrencyCodes.idr,
    englishName: 'Indonesian Rupiah',
    precision: 2,
    emojiFlag: '🇮🇩',
    englishCountryNames: {'Indonesia'},
  ),
  CurrencyCodes.ils: const Currency(
    code: CurrencyCodes.ils,
    englishName: 'Israeli New Shekel',
    precision: 2,
    emojiFlag: '🇮🇱',
    symbol: '₪',
    englishCountryNames: {'Israel'},
  ),
  CurrencyCodes.inr: const Currency(
    code: CurrencyCodes.inr,
    englishName: 'Indian Rupee',
    precision: 2,
    emojiFlag: '🇮🇳',
    symbol: '₹',
    englishCountryNames: {'India'},
  ),
  CurrencyCodes.iqd: const Currency(
    code: CurrencyCodes.iqd,
    englishName: 'Iraqi Dinar',
    precision: 3,
    emojiFlag: '🇮🇶',
    englishCountryNames: {'Iraq'},
  ),
  CurrencyCodes.irr: const Currency(
    code: CurrencyCodes.irr,
    englishName: 'Iranian Rial',
    precision: 0,
    emojiFlag: '🇮🇷',
    englishCountryNames: {'Iran'},
  ),
  CurrencyCodes.isk: const Currency(
    code: CurrencyCodes.isk,
    englishName: 'Icelandic Króna',
    precision: 2,
    emojiFlag: '🇮🇸',
    englishCountryNames: {'Iceland'},
  ),
  CurrencyCodes.jmd: const Currency(
    code: CurrencyCodes.jmd,
    englishName: 'Jamaican Dollar',
    precision: 2,
    emojiFlag: '🇯🇲',
    englishCountryNames: {'Jamaica'},
  ),
  CurrencyCodes.jod: const Currency(
    code: CurrencyCodes.jod,
    englishName: 'Jordanian Dinar',
    precision: 2,
    emojiFlag: '🇯🇴',
    englishCountryNames: {'Jordan'},
  ),
  CurrencyCodes.jpy: const Currency(
    code: CurrencyCodes.jpy,
    englishName: 'Japanese Yen',
    precision: 2,
    emojiFlag: '🇯🇵',
    englishCountryNames: {'Japan'},
  ),
  CurrencyCodes.kes: const Currency(
    code: CurrencyCodes.kes,
    englishName: 'Kenyan Shilling',
    precision: 2,
    emojiFlag: '🇰🇪',
    englishCountryNames: {'Kenya'},
  ),
  CurrencyCodes.kgs: const Currency(
    code: CurrencyCodes.kgs,
    englishName: 'Kyrgyzstani Som',
    precision: 2,
    emojiFlag: '🇰🇬',
    englishCountryNames: {'Kyrgyzstan'},
  ),
  CurrencyCodes.khr: const Currency(
    code: CurrencyCodes.khr,
    englishName: 'Cambodian Riel',
    precision: 2,
    emojiFlag: '🇰🇭',
    englishCountryNames: {'Cambodia'},
  ),
  CurrencyCodes.kmf: const Currency(
    code: CurrencyCodes.kmf,
    englishName: 'Comorian Franc',
    precision: 2,
    emojiFlag: '🇰🇲',
    englishCountryNames: {'Comoros'},
  ),
  CurrencyCodes.kpw: const Currency(
    code: CurrencyCodes.kpw,
    englishName: 'North Korean Won',
    precision: 2,
    emojiFlag: '🇰🇵',
    englishCountryNames: {'North Korea'},
  ),
  CurrencyCodes.krw: const Currency(
    code: CurrencyCodes.krw,
    englishName: 'South Korean Won',
    precision: 2,
    emojiFlag: '🇰🇷',
    englishCountryNames: {'South Korea'},
  ),
  CurrencyCodes.kwd: const Currency(
    code: CurrencyCodes.kwd,
    englishName: 'Kuwaiti Dinar',
    precision: 3,
    emojiFlag: '🇰🇼',
    englishCountryNames: {'Kuwait'},
  ),
  CurrencyCodes.kyd: const Currency(
    code: CurrencyCodes.kyd,
    englishName: 'Cayman Islands Dollar',
    precision: 2,
    emojiFlag: '🇰🇾',
    englishCountryNames: {'Cayman Islands'},
  ),
  CurrencyCodes.kzt: const Currency(
    code: CurrencyCodes.kzt,
    englishName: 'Kazakhstani Tenge',
    precision: 2,
    emojiFlag: '🇰🇿',
    englishCountryNames: {'Kazakhstan'},
  ),
  CurrencyCodes.lak: const Currency(
    code: CurrencyCodes.lak,
    englishName: 'Lao Kip',
    precision: 2,
    emojiFlag: '🇱🇦',
    englishCountryNames: {'Laos'},
  ),
  CurrencyCodes.lbp: const Currency(
    code: CurrencyCodes.lbp,
    englishName: 'Lebanese Pound',
    precision: 2,
    emojiFlag: '🇱🇧',
    englishCountryNames: {'Lebanon'},
  ),
  CurrencyCodes.lkr: const Currency(
    code: CurrencyCodes.lkr,
    englishName: 'Sri Lankan Rupee',
    precision: 2,
    emojiFlag: '🇱🇰',
    englishCountryNames: {'Sri Lanka'},
  ),
  CurrencyCodes.lrd: const Currency(
    code: CurrencyCodes.lrd,
    englishName: 'Liberian Dollar',
    precision: 2,
    emojiFlag: '🇱🇷',
    englishCountryNames: {'Liberia'},
  ),
  CurrencyCodes.lsl: const Currency(
    code: CurrencyCodes.lsl,
    englishName: 'Lesotho Loti',
    precision: 2,
    emojiFlag: '🇱🇸',
    englishCountryNames: {'Lesotho'},
  ),
  CurrencyCodes.lyd: const Currency(
    code: CurrencyCodes.lyd,
    englishName: 'Libyan Dinar',
    precision: 3,
    emojiFlag: '🇱🇾',
    englishCountryNames: {'Libya'},
  ),
  CurrencyCodes.mad: const Currency(
    code: CurrencyCodes.mad,
    englishName: 'Moroccan Dirham',
    precision: 2,
    emojiFlag: '🇲🇦',
    englishCountryNames: {'Morocco'},
  ),
  CurrencyCodes.mdl: const Currency(
    code: CurrencyCodes.mdl,
    englishName: 'Moldovan Leu',
    precision: 2,
    emojiFlag: '🇲🇩',
    englishCountryNames: {'Moldova'},
  ),
  CurrencyCodes.mga: const Currency(
    code: CurrencyCodes.mga,
    englishName: 'Malagasy Ariary',
    precision: 1,
    emojiFlag: '🇲🇬',
    englishCountryNames: {'Madagascar'},
  ),
  CurrencyCodes.mkd: const Currency(
    code: CurrencyCodes.mkd,
    englishName: 'Macedonian Denar',
    precision: 2,
    emojiFlag: '🇲🇰',
    englishCountryNames: {'North Macedonia'},
  ),
  CurrencyCodes.mmk: const Currency(
    code: CurrencyCodes.mmk,
    englishName: 'Myanmar Kyat',
    precision: 2,
    emojiFlag: '🇲🇲',
    englishCountryNames: {'Myanmar'},
  ),
  CurrencyCodes.mnt: const Currency(
    code: CurrencyCodes.mnt,
    englishName: 'Mongolian Tögrög',
    precision: 2,
    emojiFlag: '🇲🇳',
    englishCountryNames: {'Mongolia'},
  ),
  CurrencyCodes.mop: const Currency(
    code: CurrencyCodes.mop,
    englishName: 'Macanese Pataca',
    precision: 2,
    emojiFlag: '🇲🇴',
    englishCountryNames: {'Macau'},
  ),
  CurrencyCodes.mru: const Currency(
    code: CurrencyCodes.mru,
    englishName: 'Mauritanian Ouguiya',
    precision: 1,
    emojiFlag: '🇲🇷',
    englishCountryNames: {'Mauritania'},
  ),
  CurrencyCodes.mur: const Currency(
    code: CurrencyCodes.mur,
    englishName: 'Mauritian Rupee',
    precision: 2,
    emojiFlag: '🇲🇺',
    englishCountryNames: {'Mauritius'},
  ),
  CurrencyCodes.mvr: const Currency(
    code: CurrencyCodes.mvr,
    englishName: 'Maldivian Rufiyaa',
    precision: 2,
    emojiFlag: '🇲🇻',
    englishCountryNames: {'Maldives'},
  ),
  CurrencyCodes.mwk: const Currency(
    code: CurrencyCodes.mwk,
    englishName: 'Malawian Kwacha',
    precision: 2,
    emojiFlag: '🇲🇼',
    englishCountryNames: {'Malawi'},
  ),
  CurrencyCodes.mxn: const Currency(
    code: CurrencyCodes.mxn,
    englishName: 'Mexican Peso',
    precision: 2,
    emojiFlag: '🇲🇽',
    englishCountryNames: {'Mexico'},
  ),
  CurrencyCodes.myr: const Currency(
    code: CurrencyCodes.myr,
    englishName: 'Malaysian Ringgit',
    precision: 2,
    emojiFlag: '🇲🇾',
    englishCountryNames: {'Malaysia'},
  ),
  CurrencyCodes.mzn: const Currency(
    code: CurrencyCodes.mzn,
    englishName: 'Mozambican Metical',
    precision: 2,
    emojiFlag: '🇲🇿',
    englishCountryNames: {'Mozambique'},
  ),
  CurrencyCodes.nad: const Currency(
    code: CurrencyCodes.nad,
    englishName: 'Namibian Dollar',
    precision: 2,
    emojiFlag: '🇳🇦',
    englishCountryNames: {'Namibia'},
  ),
  CurrencyCodes.ngn: const Currency(
    code: CurrencyCodes.ngn,
    englishName: 'Nigerian Naira',
    precision: 2,
    emojiFlag: '🇳🇬',
    symbol: '₦',
    englishCountryNames: {'Nigeria'},
  ),
  CurrencyCodes.nio: const Currency(
    code: CurrencyCodes.nio,
    englishName: 'Nicaraguan Córdoba',
    precision: 2,
    emojiFlag: '🇳🇮',
    englishCountryNames: {'Nicaragua'},
  ),
  CurrencyCodes.nok: const Currency(
    code: CurrencyCodes.nok,
    englishName: 'Norwegian Krone',
    precision: 2,
    emojiFlag: '🇳🇴',
    englishCountryNames: {'Norway'},
  ),
  CurrencyCodes.npr: const Currency(
    code: CurrencyCodes.npr,
    englishName: 'Nepalese Rupee',
    precision: 2,
    emojiFlag: '🇳🇵',
    englishCountryNames: {'Nepal'},
  ),
  CurrencyCodes.nzd: const Currency(
    code: CurrencyCodes.nzd,
    englishName: 'New Zealand Dollar',
    precision: 2,
    emojiFlag: '🇳🇿',
    englishCountryNames: {'New Zealand', 'Cook Islands', 'Niue', 'Pitcairn Islands', 'Tokelau'},
  ),
  CurrencyCodes.omr: const Currency(
    code: CurrencyCodes.omr,
    englishName: 'Omani Rial',
    precision: 3,
    emojiFlag: '🇴🇲',
    englishCountryNames: {'Oman'},
  ),
  CurrencyCodes.pab: const Currency(
    code: CurrencyCodes.pab,
    englishName: 'Panamanian Balboa',
    precision: 2,
    emojiFlag: '🇵🇦',
    englishCountryNames: {'Panama'},
  ),
  CurrencyCodes.pen: const Currency(
    code: CurrencyCodes.pen,
    englishName: 'Peruvian Sol',
    precision: 2,
    emojiFlag: '🇵🇪',
    symbol: 'S/',
    englishCountryNames: {'Peru'},
  ),
  CurrencyCodes.pgk: const Currency(
    code: CurrencyCodes.pgk,
    englishName: 'Papua New Guinean Kina',
    precision: 2,
    emojiFlag: '🇵🇬',
    englishCountryNames: {'Papua New Guinea'},
  ),
  CurrencyCodes.php: const Currency(
    code: CurrencyCodes.php,
    englishName: 'Philippine Peso',
    precision: 2,
    emojiFlag: '🇵🇭',
    symbol: '₱',
    englishCountryNames: {'Philippines'},
  ),
  CurrencyCodes.pkr: const Currency(
    code: CurrencyCodes.pkr,
    englishName: 'Pakistani Rupee',
    precision: 2,
    emojiFlag: '🇵🇰',
    englishCountryNames: {'Pakistan'},
  ),
  CurrencyCodes.pln: const Currency(
    code: CurrencyCodes.pln,
    englishName: 'Polish Złoty',
    precision: 2,
    emojiFlag: '🇵🇱',
    symbol: 'zł',
    englishCountryNames: {'Poland'},
  ),
  CurrencyCodes.pyg: const Currency(
    code: CurrencyCodes.pyg,
    englishName: 'Paraguayan Guaraní',
    precision: 2,
    emojiFlag: '🇵🇾',
    symbol: '₲',
    englishCountryNames: {'Paraguay'},
  ),
  CurrencyCodes.qar: const Currency(
    code: CurrencyCodes.qar,
    englishName: 'Qatari Riyal',
    precision: 2,
    emojiFlag: '🇶🇦',
    symbol: 'QR',
    englishCountryNames: {'Qatar'},
  ),
  CurrencyCodes.ron: const Currency(
    code: CurrencyCodes.ron,
    englishName: 'Romanian Leu',
    precision: 2,
    emojiFlag: '🇷🇴',
    englishCountryNames: {'Romania'},
  ),
  CurrencyCodes.rsd: const Currency(
    code: CurrencyCodes.rsd,
    englishName: 'Serbian Dinar',
    precision: 2,
    emojiFlag: '🇷🇸',
    englishCountryNames: {'Serbia'},
  ),
  CurrencyCodes.rub: const Currency(
    code: CurrencyCodes.rub,
    englishName: 'Russian Ruble',
    precision: 2,
    emojiFlag: '🇷🇺',
    symbol: '₽',
    englishCountryNames: {'Russia'},
  ),
  CurrencyCodes.rwf: const Currency(
    code: CurrencyCodes.rwf,
    englishName: 'Rwandan Franc',
    precision: 2,
    emojiFlag: '🇷🇼',
    englishCountryNames: {'Rwanda'},
  ),
  CurrencyCodes.sar: const Currency(
    code: CurrencyCodes.sar,
    englishName: 'Saudi Riyal',
    precision: 2,
    emojiFlag: '🇸🇦',
    englishCountryNames: {'Saudi Arabia'},
  ),
  CurrencyCodes.sbd: const Currency(
    code: CurrencyCodes.sbd,
    englishName: 'Solomon Islands Dollar',
    precision: 2,
    emojiFlag: '🇸🇧',
    englishCountryNames: {'Solomon Islands'},
  ),
  CurrencyCodes.scr: const Currency(
    code: CurrencyCodes.scr,
    englishName: 'Seychellois Rupee',
    precision: 2,
    emojiFlag: '🇸🇨',
    englishCountryNames: {'Seychelles'},
  ),
  CurrencyCodes.sdg: const Currency(
    code: CurrencyCodes.sdg,
    englishName: 'Sudanese Pound',
    precision: 2,
    emojiFlag: '🇸🇩',
    englishCountryNames: {'Sudan'},
  ),
  CurrencyCodes.sek: const Currency(
    code: CurrencyCodes.sek,
    englishName: 'Swedish Krona',
    precision: 2,
    emojiFlag: '🇸🇪',
    englishCountryNames: {'Sweden'},
  ),
  CurrencyCodes.sgd: const Currency(
    code: CurrencyCodes.sgd,
    englishName: 'Singapore Dollar',
    precision: 1,
    emojiFlag: '🇸🇬',
    englishCountryNames: {'Singapore', 'Brunei'},
  ),
  CurrencyCodes.shp: const Currency(
    code: CurrencyCodes.shp,
    englishName: 'Saint Helena Pound',
    precision: 2,
    emojiFlag: '🇸🇭',
    englishCountryNames: {'Saint Helena'},
  ),
  CurrencyCodes.sle: const Currency(
    code: CurrencyCodes.sle,
    englishName: 'Sierra Leonean Leone',
    precision: 2,
    emojiFlag: '🇸🇱',
    englishCountryNames: {'Sierra Leone'},
  ),
  CurrencyCodes.sos: const Currency(
    code: CurrencyCodes.sos,
    englishName: 'Somali Shilling',
    precision: 2,
    emojiFlag: '🇸🇴',
    englishCountryNames: {'Somalia'},
  ),
  CurrencyCodes.srd: const Currency(
    code: CurrencyCodes.srd,
    englishName: 'Surinamese Dollar',
    precision: 2,
    emojiFlag: '🇸🇷',
    englishCountryNames: {'Suriname'},
  ),
  CurrencyCodes.ssp: const Currency(
    code: CurrencyCodes.ssp,
    englishName: 'South Sudanese Pound',
    precision: 2,
    emojiFlag: '🇸🇸',
    englishCountryNames: {'South Sudan'},
  ),
  CurrencyCodes.stn: const Currency(
    code: CurrencyCodes.stn,
    englishName: 'São Tomé and Príncipe Dobra',
    precision: 2,
    emojiFlag: '🇸🇹',
    englishCountryNames: {'São Tomé and Príncipe'},
  ),
  CurrencyCodes.svc: const Currency(
    code: CurrencyCodes.svc,
    englishName: 'Salvadoran Colón',
    precision: 2,
    emojiFlag: '🇸🇻',
    englishCountryNames: {'El Salvador'},
  ),
  CurrencyCodes.syp: const Currency(
    code: CurrencyCodes.syp,
    englishName: 'Syrian Pound',
    precision: 2,
    emojiFlag: '🇸🇾',
    englishCountryNames: {'Syria'},
  ),
  CurrencyCodes.szl: const Currency(
    code: CurrencyCodes.szl,
    englishName: 'Eswatini Lilangeni',
    precision: 2,
    emojiFlag: '🇸🇿',
    englishCountryNames: {'Eswatini'},
  ),
  CurrencyCodes.thb: const Currency(
    code: CurrencyCodes.thb,
    englishName: 'Thai Baht',
    precision: 2,
    emojiFlag: '🇹🇭',
    symbol: '฿',
    englishCountryNames: {'Thailand'},
  ),
  CurrencyCodes.tjs: const Currency(
    code: CurrencyCodes.tjs,
    englishName: 'Tajikistani Somoni',
    precision: 2,
    emojiFlag: '🇹🇯',
    englishCountryNames: {'Tajikistan'},
  ),
  CurrencyCodes.tmt: const Currency(
    code: CurrencyCodes.tmt,
    englishName: 'Turkmenistani Manat',
    precision: 2,
    emojiFlag: '🇹🇲',
    englishCountryNames: {'Turkmenistan'},
  ),
  CurrencyCodes.tnd: const Currency(
    code: CurrencyCodes.tnd,
    englishName: 'Tunisian Dinar',
    precision: 3,
    emojiFlag: '🇹🇳',
    englishCountryNames: {'Tunisia'},
  ),
  CurrencyCodes.top: const Currency(
    code: CurrencyCodes.top,
    englishName: 'Tongan Paʻanga',
    precision: 2,
    emojiFlag: '🇹🇴',
    englishCountryNames: {'Tonga'},
  ),
  CurrencyCodes.tryCode: const Currency(
    code: CurrencyCodes.tryCode,
    englishName: 'Turkish Lira',
    precision: 2,
    emojiFlag: '🇹🇷',
    symbol: '₺',
    englishCountryNames: {'Turkey'},
  ),
  CurrencyCodes.ttd: const Currency(
    code: CurrencyCodes.ttd,
    englishName: 'Trinidad and Tobago Dollar',
    precision: 2,
    emojiFlag: '🇹🇹',
    englishCountryNames: {'Trinidad and Tobago'},
  ),
  CurrencyCodes.twd: const Currency(
    code: CurrencyCodes.twd,
    englishName: 'New Taiwan Dollar',
    precision: 2,
    emojiFlag: '🇹🇼',
    englishCountryNames: {'Taiwan'},
  ),
  CurrencyCodes.tzs: const Currency(
    code: CurrencyCodes.tzs,
    englishName: 'Tanzanian Shilling',
    precision: 2,
    emojiFlag: '🇹🇿',
    englishCountryNames: {'Tanzania'},
  ),
  CurrencyCodes.uah: const Currency(
    code: CurrencyCodes.uah,
    englishName: 'Ukrainian Hryvnia',
    precision: 2,
    emojiFlag: '🇺🇦',
    englishCountryNames: {'Ukraine'},
  ),
  CurrencyCodes.ugx: const Currency(
    code: CurrencyCodes.ugx,
    englishName: 'Ugandan Shilling',
    precision: 2,
    emojiFlag: '🇺🇬',
    englishCountryNames: {'Uganda'},
  ),
  CurrencyCodes.usd: const Currency(
    code: CurrencyCodes.usd,
    englishName: 'United States Dollar',
    precision: 2,
    emojiFlag: '🇺🇸',
    symbol: '\$',
    englishCountryNames: {
      'United States',
      'Ecuador',
      'El Salvador',
      'Panama',
      'East Timor',
      'Zimbabwe',
      'Micronesia',
      'Palau',
      'Marshall Islands',
      'Caribbean Netherlands',
      'Turks and Caicos Islands',
      'British Virgin Islands',
    },
  ),
  CurrencyCodes.uyu: const Currency(
    code: CurrencyCodes.uyu,
    englishName: 'Uruguayan Peso',
    precision: 2,
    emojiFlag: '🇺🇾',
    englishCountryNames: {'Uruguay'},
  ),
  CurrencyCodes.uzs: const Currency(
    code: CurrencyCodes.uzs,
    englishName: 'Uzbekistani Som',
    precision: 2,
    emojiFlag: '🇺🇿',
    englishCountryNames: {'Uzbekistan'},
  ),
  CurrencyCodes.ved: const Currency(
    code: CurrencyCodes.ved,
    englishName: 'Venezuelan Bolívar Digital',
    precision: 2,
    emojiFlag: '🇻🇪',
    englishCountryNames: {'Venezuela'},
  ),
  CurrencyCodes.ves: const Currency(
    code: CurrencyCodes.ves,
    englishName: 'Venezuelan Bolívar Soberano',
    precision: 0,
    emojiFlag: '🇻🇪',
    englishCountryNames: {'Venezuela'},
  ),
  CurrencyCodes.vnd: const Currency(
    code: CurrencyCodes.vnd,
    englishName: 'Vietnamese Đồng',
    precision: 2,
    emojiFlag: '🇻🇳',
    symbol: '₫',
    englishCountryNames: {'Vietnam'},
  ),
  CurrencyCodes.vuv: const Currency(
    code: CurrencyCodes.vuv,
    englishName: 'Vanuatu Vatu',
    precision: 2,
    emojiFlag: '🇻🇺',
    englishCountryNames: {'Vanuatu'},
  ),
  CurrencyCodes.wst: const Currency(
    code: CurrencyCodes.wst,
    englishName: 'Samoan Tala',
    precision: 2,
    emojiFlag: '🇼🇸',
    englishCountryNames: {'Samoa'},
  ),
  CurrencyCodes.xaf: const Currency(
    code: CurrencyCodes.xaf,
    englishName: 'Central African CFA Franc',
    precision: 2,
    emojiFlag: '🇨🇲',
    englishCountryNames: {
      'Cameroon',
      'Central African Republic',
      'Chad',
      'Republic of the Congo',
      'Equatorial Guinea',
      'Gabon',
    },
  ),
  CurrencyCodes.xcd: const Currency(
    code: CurrencyCodes.xcd,
    englishName: 'East Caribbean Dollar',
    precision: 2,
    emojiFlag: '🇦🇮',
    englishCountryNames: {
      'Anguilla',
      'Antigua and Barbuda',
      'Dominica',
      'Grenada',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Vincent and the Grenadines',
      'Montserrat',
    },
  ),
  CurrencyCodes.xof: const Currency(
    code: CurrencyCodes.xof,
    englishName: 'West African CFA Franc',
    precision: 2,
    emojiFlag: '🇧🇯',
    englishCountryNames: {
      'Benin',
      'Burkina Faso',
      "Côte d'Ivoire",
      'Guinea-Bissau',
      'Mali',
      'Niger',
      'Senegal',
      'Togo',
    },
  ),
  CurrencyCodes.xpf: const Currency(
    code: CurrencyCodes.xpf,
    englishName: 'CFP Franc',
    precision: 2,
    emojiFlag: '🇵🇫',
    englishCountryNames: {'French Polynesia', 'New Caledonia', 'Wallis and Futuna'},
  ),
  CurrencyCodes.yer: const Currency(
    code: CurrencyCodes.yer,
    englishName: 'Yemeni Rial',
    precision: 2,
    emojiFlag: '🇾🇪',
    englishCountryNames: {'Yemen'},
  ),
  CurrencyCodes.zar: const Currency(
    code: CurrencyCodes.zar,
    englishName: 'South African Rand',
    precision: 2,
    emojiFlag: '🇿🇦',
    englishCountryNames: {'South Africa'},
  ),
  CurrencyCodes.zmw: const Currency(
    code: CurrencyCodes.zmw,
    englishName: 'Zambian Kwacha',
    precision: 2,
    emojiFlag: '🇿🇲',
    englishCountryNames: {'Zambia'},
  ),
};
